// SPDX-License-Identifier: MIT
// SchemaCommand.swift - Database schema inspection

import ArgumentParser
import Foundation
import GRDB
#if os(macOS)
import ContextifyCore
#else
import ContextifyIngestionCore
#endif

struct SchemaCommand: ParsableCommand {
  static let configuration = CommandConfiguration(
    commandName: "schema",
    abstract: "Inspect database schema",
    subcommands: [DumpSubcommand.self, VersionSubcommand.self],
    defaultSubcommand: DumpSubcommand.self
  )
}

// MARK: - Dump Subcommand

extension SchemaCommand {
  struct DumpSubcommand: ParsableCommand {
    static let configuration = CommandConfiguration(
      commandName: "dump",
      abstract: "Dump the complete database schema"
    )

    @Option(name: .long, help: "Path to the SQLite database file")
    var db: String

    @Option(name: .long, help: "Output format: sql or json")
    var format: OutputFormat = .sql

    enum OutputFormat: String, ExpressibleByArgument {
      case sql, json
    }

    mutating func run() throws {
      // FTS5 preflight
      let pool = try DatabaseOpener.openDatabase(at: db)

      let schema = try pool.read { db -> [TableInfo] in
        // Get list of tables
        let tables = try String.fetchAll(db, sql: """
          SELECT name FROM sqlite_master
          WHERE type='table' AND name NOT LIKE 'sqlite_%'
          ORDER BY name
        """)

        var result: [TableInfo] = []
        for tableName in tables {
          // Get CREATE statement
          let createSQL = try String.fetchOne(db, sql: """
            SELECT sql FROM sqlite_master WHERE type='table' AND name=?
          """, arguments: [tableName]) ?? ""

          // Get column info
          let columns = try Row.fetchAll(db, sql: "PRAGMA table_info('\(tableName)')")
          let columnInfos = columns.map { row -> ColumnInfo in
            ColumnInfo(
              name: row["name"] as? String ?? "",
              type: row["type"] as? String ?? "",
              notNull: (row["notnull"] as? Int ?? 0) == 1,
              primaryKey: (row["pk"] as? Int ?? 0) > 0,
              defaultValue: row["dflt_value"] as? String
            )
          }

          // Get indexes
          let indexes = try Row.fetchAll(db, sql: "PRAGMA index_list('\(tableName)')")
          let indexInfos = indexes.map { row -> IndexInfo in
            IndexInfo(
              name: row["name"] as? String ?? "",
              unique: (row["unique"] as? Int ?? 0) == 1
            )
          }

          result.append(TableInfo(
            name: tableName,
            createSQL: createSQL,
            columns: columnInfos,
            indexes: indexInfos
          ))
        }
        return result
      }

      // Output
      switch format {
      case .sql:
        printSQLFormat(schema)
      case .json:
        printJSONFormat(schema)
      }
    }

    private func printSQLFormat(_ schema: [TableInfo]) {
      print("-- Contextify Database Schema")
      print("-- Generated by contextify-ingest schema dump")
      print("")

      for table in schema {
        print("-- Table: \(table.name)")
        print(table.createSQL)
        print("")

        if !table.indexes.isEmpty {
          print("-- Indexes for \(table.name):")
          for index in table.indexes {
            let uniqueStr = index.unique ? "UNIQUE " : ""
            print("-- \(uniqueStr)INDEX \(index.name)")
          }
          print("")
        }
      }
    }

    private func printJSONFormat(_ schema: [TableInfo]) {
      let output: [[String: Any]] = schema.map { table in
        [
          "name": table.name,
          "sql": table.createSQL,
          "columns": table.columns.map { col in
            [
              "name": col.name,
              "type": col.type,
              "notNull": col.notNull,
              "primaryKey": col.primaryKey,
              "default": col.defaultValue as Any
            ]
          },
          "indexes": table.indexes.map { idx in
            ["name": idx.name, "unique": idx.unique]
          }
        ]
      }

      if let data = try? JSONSerialization.data(withJSONObject: output, options: .prettyPrinted),
         let json = String(data: data, encoding: .utf8) {
        print(json)
      }
    }
  }
}

// MARK: - Version Subcommand

extension SchemaCommand {
  struct VersionSubcommand: ParsableCommand {
    static let configuration = CommandConfiguration(
      commandName: "version",
      abstract: "Show schema version"
    )

    @Option(name: .long, help: "Path to the SQLite database file")
    var db: String

    mutating func run() throws {
      var config = Configuration()
      config.readonly = true

      let pool = try DatabasePool(path: db, configuration: config)

      let version = try pool.read { db in
        try Int.fetchOne(db, sql: "PRAGMA user_version") ?? 0
      }

      print("Schema version: \(version)")
      print("Expected version: \(DatabaseSchema.currentVersion)")

      if version < DatabaseSchema.currentVersion {
        print("Status: Database needs migration")
      } else if version > DatabaseSchema.currentVersion {
        print("Status: Database is newer than this CLI version")
      } else {
        print("Status: Up to date")
      }
    }
  }
}

// MARK: - Supporting Types

private struct TableInfo {
  let name: String
  let createSQL: String
  let columns: [ColumnInfo]
  let indexes: [IndexInfo]
}

private struct ColumnInfo {
  let name: String
  let type: String
  let notNull: Bool
  let primaryKey: Bool
  let defaultValue: String?
}

private struct IndexInfo {
  let name: String
  let unique: Bool
}
